// src/components/Navbar.tsx
export function Navbar() {
  return (
    <nav className="text-xl">
      <div className="flex justify-center space-x-4">
        <a
          href="https://s.ferg.al/github"
          target="_blank"
          rel="noreferrer"
          className="flex items-center px-3 py-2 font-medium text-gray-300 rounded-md hover:bg-gray-700 hover:text-white"
        >
          <i className="mr-1 fa-brands fa-github" />
          Github
        </a>
        <a
          href="https://s.ferg.al/mixcloud"
          target="_blank"
          rel="noreferrer"
          className="px-3 py-2 font-medium text-gray-300 rounded-md hover:bg-gray-700 hover:text-white"
        >
          <i className="mr-1 fa-brands fa-mixcloud" />
          Mixcloud
        </a>
        <a
          href="https://s.ferg.al/soundcloud"
          target="_blank"
          rel="noreferrer"
          className="px-3 py-2 font-medium text-gray-300 rounded-md hover:bg-gray-700 hover:text-white"
        >
          <i className="mr-1 fa-brands fa-soundcloud" />
          Soundcloud
        </a>
        <a
          href="https://s.ferg.al/mixes"
          target="_blank"
          rel="noreferrer"
          className="px-3 py-2 font-medium text-gray-300 rounded-md hover:bg-gray-700 hover:text-white"
        >
          <i className="mr-1 fa-solid fa-headphones" />
          Music
        </a>
        <a
          href="https://s.ferg.al/youtube"
          target="_blank"
          rel="noreferrer"
          className="flex items-center px-3 py-2 font-medium text-gray-300 rounded-md hover:bg-gray-700 hover:text-white"
        >
          <i className="mr-1 fa-brands fa-youtube" />
          YouTube
        </a>
        <a
          href="https://s.ferg.al/mastodon"
          rel="me"
          target="_blank"
          className="px-3 py-2 font-medium text-gray-300 rounded-md hover:bg-gray-700 hover:text-white"
        >
          <i className="mr-1 fa-brands fa-mastodon" />
          Mastodon
        </a>
        <a
          href="https://s.ferg.al/bluesky"
          rel="me"
          target="_blank"
          className="px-3 py-2 font-medium text-gray-300 rounded-md hover:bg-gray-700 hover:text-white"
        >
          <i className="mr-1 fa-brands fa-bluesky" />
          Bluesky
        </a>
      </div>
    </nav>
  )
}

// src/lib/components/Navbar.svelte
<nav class="text-xl">
	<div class="flex justify-center space-x-4">
		<a
			href="https://s.ferg.al/github"
			target="_blank"
			class="flex items-center px-3 py-2 font-medium text-gray-300 rounded-md hover:bg-gray-700 hover:text-white"
		>
			<i class="mr-1 fa-brands fa-github" />
			Github</a
		>
		<a
			href="https://s.ferg.al/mixcloud"
			target="_blank"
			class="px-3 py-2 font-medium text-gray-300 rounded-md hover:bg-gray-700 hover:text-white"
		>
			<i class="mr-1 fa-brands fa-mixcloud" />
			Mixcloud</a
		>
		<a
			href="https://s.ferg.al/soundcloud"
			target="_blank"
			class="px-3 py-2 font-medium text-gray-300 rounded-md hover:bg-gray-700 hover:text-white"
		>
			<i class="mr-1 fa-brands fa-soundcloud" />
			Soundcloud</a
		>
		<a
			href="https://s.ferg.al/mixes"
			target="_blank"
			class="px-3 py-2 font-medium text-gray-300 rounded-md hover:bg-gray-700 hover:text-white"
		>
			<i class="mr-1 fa-solid fa-headphones" />
			Music</a
		>
		<a
			href="https://s.ferg.al/youtube"
			target="_blank"
			class="flex items-center px-3 py-2 font-medium text-gray-300 rounded-md hover:bg-gray-700 hover:text-white"
		>
			<i class="mr-1 fa-brands fa-youtube" />
			YouTube
		</a>
		<a
			href="https://s.ferg.al/mastodon"
			rel="me"
			target="_blank"
			class="px-3 py-2 font-medium text-gray-300 rounded-md hover:bg-gray-700 hover:text-white"
		>
			<i class="mr-1 fa-brands fa-mastodon" />
			Mastodon</a
		>
		<a
			href="https://s.ferg.al/bluesky"
			rel="me"
			target="_blank"
			class="px-3 py-2 font-medium text-gray-300 rounded-md hover:bg-gray-700 hover:text-white"
		>
			<i class="mr-1 fa-brands fa-bluesky"></i>
			Bluesky</a
		>
	</div>
</nav>
